# Generated by Django 4.2.4 on 2023-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, verbose_name='Госномер авто')),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('steering_wheel', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
